#!/usr/bin/env bash
# scripts/mac/install-launchagent.sh
# Generates and installs a LaunchAgent that auto-mounts the SMB share and
# attaches the sparsebundle on login and after network wake.
#
# Requires: the sparsebundle to already exist on the share (run create-sparsebundle.sh first)
# Requires: SMB credentials saved in Keychain for the share
#
# Usage: bash scripts/mac/install-launchagent.sh
#   Or non-interactively:
#     SHARE_HOST=myserver SHARE_NAME=MyShare bash scripts/mac/install-launchagent.sh

set -euo pipefail

COMPUTER=$(scutil --get ComputerName)
UUID=$(system_profiler SPHardwareDataType | awk '/Hardware UUID/{print $3}')
BUNDLE_NAME="${COMPUTER}_${UUID}.sparsebundle"
LABEL="com.$(echo "$COMPUTER" | tr '[:upper:]' '[:lower:]' | tr ' ' '-').timemachine-mount"
SCRIPT_DIR="$HOME/Library/Scripts"
SCRIPT_PATH="$SCRIPT_DIR/mount-timemachine.sh"
PLIST_PATH="$HOME/Library/LaunchAgents/${LABEL}.plist"
LOG_PATH="$HOME/Library/Logs/timemachine-mount.log"

echo "=== AO_TimeMachine: Install LaunchAgent ==="
echo "  Machine : $COMPUTER"
echo "  Bundle  : $BUNDLE_NAME"
echo "  Label   : $LABEL"
echo ""

# --- Gather inputs ---

if [ -z "${SHARE_HOST:-}" ]; then
    echo "Enter the hostname or IP of the SMB server (e.g. adbel, 192.168.1.50):"
    read -r SHARE_HOST
fi

if [ -z "${SHARE_NAME:-}" ]; then
    echo "Enter the SMB share name (e.g. IntelMBP_TimeMachine):"
    read -r SHARE_NAME
fi

SHARE_URL="smb://${SHARE_HOST}/${SHARE_NAME}"
SHARE_VOLUME="/Volumes/${SHARE_NAME}"
SPARSEBUNDLE_PATH="${SHARE_VOLUME}/${BUNDLE_NAME}"
TM_VOLUME="/Volumes/Time Machine"
USERNAME=$(id -un)

# --- Generate mount script ---

mkdir -p "$SCRIPT_DIR"
mkdir -p "$HOME/Library/Logs"

cat > "$SCRIPT_PATH" << MOUNT_SCRIPT
#!/usr/bin/env bash
# Auto-generated by AO_TimeMachine install-launchagent.sh
# Machine: ${COMPUTER}  UUID: ${UUID}
# Share:   ${SHARE_URL}
# Bundle:  ${BUNDLE_NAME}
# DO NOT EDIT — regenerate via scripts/mac/install-launchagent.sh

set -uo pipefail

SHARE_URL="${SHARE_URL}"
SHARE_VOLUME="${SHARE_VOLUME}"
SPARSEBUNDLE_PATH="${SPARSEBUNDLE_PATH}"
TM_VOLUME="${TM_VOLUME}"
LOG="${LOG_PATH}"

log() { echo "\$(date '+%Y-%m-%d %H:%M:%S') \$*" >> "\$LOG"; }
log "--- mount-timemachine starting ---"

# Wait for host to be reachable (up to 2 minutes)
REACHABLE=0
for i in \$(seq 1 24); do
    if /sbin/ping -c1 -W1000 "${SHARE_HOST}" &>/dev/null; then
        log "Host ${SHARE_HOST} reachable after \${i}x5s"
        REACHABLE=1
        break
    fi
    sleep 5
done

if [ "\$REACHABLE" -eq 0 ]; then
    log "ERROR: ${SHARE_HOST} not reachable after 2 minutes — aborting"
    exit 1
fi

# Mount SMB share if not already mounted
if [ ! -d "\$SHARE_VOLUME" ]; then
    log "Mounting \$SHARE_URL ..."
    osascript -e "mount volume \"\$SHARE_URL\"" >> "\$LOG" 2>&1
    sleep 5
fi

if [ ! -d "\$SHARE_VOLUME" ]; then
    log "ERROR: Share did not mount at \$SHARE_VOLUME"
    exit 1
fi
log "Share mounted: \$SHARE_VOLUME"

# Attach sparsebundle if not already attached
if [ ! -d "\$TM_VOLUME" ]; then
    log "Attaching sparsebundle: \$SPARSEBUNDLE_PATH ..."
    hdiutil attach "\$SPARSEBUNDLE_PATH" -nobrowse -quiet >> "\$LOG" 2>&1
    sleep 3
fi

if [ ! -d "\$TM_VOLUME" ]; then
    log "ERROR: Sparsebundle did not mount at \$TM_VOLUME"
    exit 1
fi
log "Sparsebundle mounted at \$TM_VOLUME — Time Machine will run on next schedule"
MOUNT_SCRIPT

chmod +x "$SCRIPT_PATH"
echo "✅ Mount script written: $SCRIPT_PATH"

# --- Generate LaunchAgent plist ---

cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${SCRIPT_PATH}</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>StandardOutPath</key>
    <string>${LOG_PATH}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_PATH}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
</dict>
</plist>
PLIST

echo "✅ LaunchAgent plist written: $PLIST_PATH"

# --- Unload old version if present, then load ---

launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

echo ""
echo "✅ LaunchAgent loaded: $LABEL"
echo "   Log: $LOG_PATH"
echo ""
echo "Now set the Time Machine destination (run once in Terminal with Full Disk Access):"
echo "  sudo tmutil setdestination \"/Volumes/Time Machine\""
echo ""
echo "Then start backup:"
echo "  sudo tmutil startbackup"
